version: 2.1
executors:
  ruby:
    docker: [ image: circleci/ruby ]
  chef:
    machine: true
jobs:
  danger:
    executor: ruby
    steps:
      - checkout
      - run:
          name: Install Danger
          command: gem install danger
      - run:
          name: Run Danger
          command: danger
  lint:
    executor: ruby
    parameters:
      channel:
        description: ChefDK channel stable or current
        type: string
        default: current
    steps:
      - checkout
      - run:
          name: Install Chef
          command: curl -L https://omnitruck.chef.io/install.sh | sudo bash -s -- -c <<parameters.channel>> -P chefdk
      - run:
          name: Unit Test
          command: chef exec delivery local all
  dokken:
    executor: chef
    parameters:
      suite:
        description: Test Kitchen suite name
        type: string
      channel:
        description: ChefDK channel stable or current
        type: string
        default: current
    environment:
      KITCHEN_LOCAL_YAML: .kitchen.dokken.yml
    steps:
      - checkout
      - run:
          name: Install Chef
          command: curl -L https://omnitruck.chef.io/install.sh | sudo bash -s -- -c <<parameters.channel>> -P chefdk
      # - run:
      #     name: amazonlinux
      #     command: kitchen test <<parameters.suite>>-amazonlinux
      - run:
          name: centos-6
          command: kitchen test <<parameters.suite>>-centos-6
      - run:
          name: centos-7
          command: kitchen test <<parameters.suite>>-centos-7
      - run:
          name: debian-8
          command: kitchen test <<parameters.suite>>-debian-8
      - run:
          name: debian-9
          command: kitchen test <<parameters.suite>>-debian-9
      - run:
          name: fedora-latest
          command: kitchen test <<parameters.suite>>-fedora-latest
      - run:
          name: ubuntu-16.04
          command: kitchen test <<parameters.suite>>-ubuntu-1604
      - run:
          name: ubuntu-18.04
          command: kitchen test <<parameters.suite>>-ubuntu-1604
  dokken-single:
    executor: chef
    parameters:
      suite:
        description: Test Kitchen suite name
        type: string
      platform:
        description: Test platform
        type: string
      channel:
        description: ChefDK channel stable or current
        type: string
        default: current
    environment:
      KITCHEN_LOCAL_YAML: .kitchen.dokken.yml
    steps:
      - checkout
      - run:
          name: Install Chef
          command: curl -L https://omnitruck.chef.io/install.sh | sudo bash -s -- -c <<parameters.channel>> -P chefdk
      - run:
          command: kitchen test <<parameters.suite>>-<<parameters.platform>>
