---
version: 2.1

executors:
  delivery:
    docker: [image: "chef/chefdk:3"]
  ruby:
    docker: [image: "circleci/ruby"]
  python:
    docker: [image: "circleci/python"]
  chef:
    machine: true

commands:
  install_chef:
    description: Installs Chef Development Kit
    parameters:
      channel:
        description: ChefDK channel stable or current
        type: string
        default: current
    steps:
      - run:
          name: Install Chef
          command: curl -L https://omnitruck.chef.io/install.sh |
                    sudo bash -s -- -c <<parameters.channel>> -P chefdk
jobs:
  danger:
    executor: ruby
    steps:
      - checkout
      - run:
          name: Install Danger
          command: gem install danger
      - run:
          name: Run Danger
          command: danger
  delivery:
    executor: delivery
    steps:
      - checkout
      - run:
          name: Run delivery
          command: delivery local all
  dokken:
    executor: chef
    parameters:
      suite:
        description: Test Kitchen suite name
        type: string
      channel:
        description: ChefDK channel stable or current
        type: string
        default: current
    environment:
      KITCHEN_LOCAL_YAML: .kitchen.dokken.yml
    steps:
      - checkout
      - install_chef
      - run:
          name: amazonlinux
          no_output_timeout: 1.25h
          command: kitchen test <<parameters.suite>>-amazonlinux
      - run:
          name: amazonlinux-2
          no_output_timeout: 1.25h
          command: kitchen test <<parameters.suite>>-amazonlinux-2
      - run:
          name: centos-6
          no_output_timeout: 1.25h
          command: kitchen test <<parameters.suite>>-centos-6
      - run:
          name: centos-7
          no_output_timeout: 1.25h
          command: kitchen test <<parameters.suite>>-centos-7
      - run:
          name: debian-8
          no_output_timeout: 1.25h
          command: kitchen test <<parameters.suite>>-debian-8
      - run:
          name: debian-9
          no_output_timeout: 1.25h
          command: kitchen test <<parameters.suite>>-debian-9
      - run:
          name: ubuntu-16.04
          no_output_timeout: 1.25h
          command: kitchen test <<parameters.suite>>-ubuntu-1604
      - run:
          name: ubuntu-18.04
          no_output_timeout: 1.25h
          command: kitchen test <<parameters.suite>>-ubuntu-1804
  dokken-single:
    executor: chef
    parameters:
      suite:
        description: Test Kitchen suite name
        type: string
      platform:
        description: Test platform
        type: string
      channel:
        description: ChefDK channel stable or current
        type: string
        default: current
    environment:
      KITCHEN_LOCAL_YAML: .kitchen.dokken.yml
    steps:
      - checkout
      - install_chef
      - run:
          command: kitchen test <<parameters.suite>>-<<parameters.platform>>
  mdlint:
    executor: ruby
    steps:
      - checkout
      - run:
          name: Install Markdown Linter
          command: gem install mdl
      - run:
          name: Run Markdown Linter
          command: mdl ./
  yamllint:
    executor: python
    steps:
      - checkout
      - run:
          name: Install YamlLint
          command: pip install --user yamllint
      - run:
          name: Run YamlLint
          command: |
            export PATH=/home/circleci/.local/bin:$PATH
            yamllint .
